apiVersion: apps/v1
kind: Deployment
metadata:
  name: ben-httpserver-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ben-httpserver-metrics
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: ben-httpserver-metrics
    spec:
      containers:
        - name: ben-httpserver-metrics
          imagePullPolicy: Always
          image: docker.io/njq0506/httpserver:v1.0.6
          ports:
          - containerPort: 80
